DROP TABLE IF EXISTS genre_film;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film_user;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
--DROP TABLE IF EXISTS STATUS_FRIENDS;
DROP TABLE IF EXISTS MPA;
DROP TABLE IF EXISTS GENRE;
--

-- genre definition

-- Drop table

-- DROP TABLE genre;

CREATE TABLE IF NOT EXISTS genre (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL,
	CONSTRAINT genre_pk PRIMARY KEY (id)
);


-- mpa definition

-- Drop table

-- DROP TABLE mpa;

CREATE TABLE IF NOT EXISTS mpa (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL,
	CONSTRAINT mpa_pk PRIMARY KEY (id)
);

-- user definition

-- Drop table

-- DROP TABLE user;

CREATE TABLE IF NOT EXISTS users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar NOT NULL,
	login varchar NOT NULL,
	name varchar NULL,
	birthday date NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id)
);


-- film definition

-- Drop table

-- DROP TABLE film;

CREATE TABLE IF NOT EXISTS films (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL,
	description varchar NULL,
	releasedate date NOT NULL,
	duration int4 NOT NULL,
	mpa_id int4 NOT NULL,
	rate int4 NOT NULL,
	CONSTRAINT film_pk PRIMARY KEY (id),
	CONSTRAINT film_fk FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);


-- film_user definition

-- Drop table

-- DROP TABLE film_user;

CREATE TABLE IF NOT EXISTS film_user (
	id_film int4 NOT NULL,
	id_user int4 NOT NULL,
	CONSTRAINT film_user_fk FOREIGN KEY (id_film) REFERENCES films(id),
	CONSTRAINT film_user_fk_1 FOREIGN KEY (id_user) REFERENCES users(id)
);


-- friends definition

-- Drop table

-- DROP TABLE friends;

CREATE TABLE IF NOT EXISTS friends (
	id_user1 int4 NOT NULL,
	id_user2 int4 NOT NULL,
	CONSTRAINT friends_un UNIQUE (id_user2, id_user1),
	CONSTRAINT status_friends_fk FOREIGN KEY (id_user1) REFERENCES users(id),
	CONSTRAINT status_friends_fk_1 FOREIGN KEY (id_user2) REFERENCES users(id)
);


-- genre_film definition

-- Drop table

-- DROP TABLE genre_film;

CREATE TABLE IF NOT EXISTS genre_film (
	id_genre int4 NOT NULL,
	id_film int4 NOT NULL,
    CONSTRAINT genre_film_UN UNIQUE (id_film, id_genre),
	CONSTRAINT genre_film_fk FOREIGN KEY (id_film) REFERENCES films(id),
	CONSTRAINT genre_film_fk_1 FOREIGN KEY (id_genre) REFERENCES genre(id)
);